project:
  type: website

website:
  title: "Priscilla Dixon"
  navbar:
    right:
      - href: index.qmd
        text: Home
      # about.qmd
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: lux
    css: styles.css

editor: visual

execute:
  freeze: auto
